import { useEffect, useMemo, useState } from 'react'
import { Activity, CheckCircle2, ChevronRight, Cloud, FolderOpen, Link2, Loader2, MonitorUp, Pause, Play, RefreshCw, Settings2, TriangleAlert, Video } from 'lucide-react'
import type { AppSettings, AppSnapshot, Recording, RecordingDateFormat, SettingsInput } from '../shared/types'

const empty: AppSnapshot = { settings: { descriptDestinationRoot: '', recordingTimezone: Intl.DateTimeFormat().resolvedOptions().timeZone, recordingDateFormat: 'yyyy-MM-dd', recordingsDirectory: null, reconciliationDirectory: null, obsHost: '127.0.0.1', obsPort: 4455 }, hasDescriptToken: false, connections: { obs: 'disconnected', descript: 'disconnected', watcher: 'stopped' }, recordings: [], activity: [], activeRecording: null }
const today = (settings: AppSettings) => {
  const parts = new Intl.DateTimeFormat('en-US', { timeZone: settings.recordingTimezone, year: 'numeric', month: 'numeric', day: 'numeric' }).formatToParts(new Date())
  const value = (kind: string) => parts.find((part) => part.type === kind)?.value ?? ''
  const year = value('year'); const month = value('month'); const day = value('day')
  if (settings.recordingDateFormat === 'M.d.yyyy') return `${month}.${day}.${year}`
  if (settings.recordingDateFormat === 'MM.dd.yyyy') return `${month.padStart(2, '0')}.${day.padStart(2, '0')}.${year}`
  return `${year}-${month.padStart(2, '0')}-${day.padStart(2, '0')}`
}

export function App() {
  const [data, setData] = useState<AppSnapshot>(empty)
  const [busy, setBusy] = useState(false)
  const [notice, setNotice] = useState<{ message: string; tone: 'success' | 'error' } | null>(null)
  const load = () => window.desktopApi.getSnapshot().then(setData)
  useEffect(() => { void load(); return window.desktopApi.onStateChanged(setData) }, [])
  const configured = Boolean(data.settings.recordingsDirectory)
  const counts = useMemo(() => data.recordings.reduce<Record<string, number>>((sum, recording) => { sum[recording.status] = (sum[recording.status] ?? 0) + 1; return sum }, {}), [data.recordings])
  const action = async (work: () => Promise<unknown>) => { setBusy(true); setNotice(null); try { await work(); await load() } catch (error) { setNotice({ message: error instanceof Error ? error.message : String(error), tone: 'error' }) } finally { setBusy(false) } }
  return <div className="app-shell">
    <main className="content">{notice && <div className={`notice ${notice.tone}`}>{notice.tone === 'success' ? <CheckCircle2 size={17}/> : <TriangleAlert size={17}/>}<span>{notice.message}</span><button onClick={() => setNotice(null)}>×</button></div>}
      <Dashboard data={data} counts={counts} busy={busy} configured={configured} onSettings={() => document.getElementById('settings')?.scrollIntoView({ behavior: 'smooth', block: 'start' })} onAction={action}/>
      <div id="settings" className="settings-anchor"><Settings data={data} busy={busy} onSave={async (input) => { await action(() => window.desktopApi.saveSettings(input)) }} onCancel={() => window.scrollTo({ top: 0, behavior: 'smooth' })} onTest={(token) => action(async () => { const result = await window.desktopApi.testDescript(token); if (!result.ok) throw new Error(result.message); setNotice({ message: result.message, tone: 'success' }) })} onObs={(input) => action(async () => { const result = await window.desktopApi.connectObs(input); if (!result.ok) throw new Error(result.message); setNotice({ message: result.message, tone: 'success' }) })}/></div></main>
  </div>
}

function Dashboard({ data, counts, busy, configured, onSettings, onAction }: { data: AppSnapshot; counts: Record<string, number>; busy: boolean; configured: boolean; onSettings: () => void; onAction: (work: () => Promise<unknown>) => Promise<void> }) {
  const destination = [data.settings.descriptDestinationRoot, today(data.settings)].filter(Boolean).join('/')
  const monitoring = data.connections.watcher === 'watching'
  return <><header className="page-header"><div><p className="eyebrow">RECORDINGS</p><h1>OBS → Descript</h1></div><div className="header-actions"><button className="button secondary" disabled={busy} onClick={() => onAction(() => window.desktopApi.reconcile())}><RefreshCw size={16} className={busy ? 'spin' : ''}/>Reconcile</button><button className="button primary" disabled={busy || !configured} onClick={() => onAction(() => monitoring ? window.desktopApi.stopMonitoring() : window.desktopApi.startMonitoring())}>{monitoring ? <Pause size={16}/> : <Play size={16}/>}{monitoring ? 'Pause' : 'Start monitoring'}</button></div></header>
  {!configured && <section className="setup-callout"><div className="callout-icon"><Settings2 size={21}/></div><div><h2>Setup required</h2><p>Connect to OBS and add a Descript API token.</p></div><button className="button primary" onClick={onSettings}>Configure <ChevronRight size={16}/></button></section>}
  <section className="connection-grid"><Connection icon={<MonitorUp size={19}/>} title="OBS" value={data.connections.obs === 'connected' ? 'Connected' : 'Not connected'} detail={`${data.settings.obsHost}:${data.settings.obsPort}`} state={data.connections.obs} action={data.connections.obs === 'connected' ? undefined : { label: 'Connect', onClick: () => onAction(async () => { const result = await window.desktopApi.connectObs({ host: data.settings.obsHost, port: data.settings.obsPort }); if (!result.ok) throw new Error(result.message) }) }}/><Connection icon={<Cloud size={19}/>} title="Descript" value={data.connections.descript === 'connected' ? 'Token verified' : data.connections.descript === 'rejected' ? 'Token rejected' : data.hasDescriptToken ? 'Token saved' : 'No token saved'} detail={data.connections.descript === 'connected' ? 'Descript API connected' : data.connections.descript === 'rejected' ? 'Replace it in Settings' : data.hasDescriptToken ? 'Stored securely in Keychain' : 'Add a token in Settings'} state={data.connections.descript === 'connected' ? 'connected' : data.connections.descript === 'rejected' ? 'rejected' : data.hasDescriptToken ? 'saved' : 'disconnected'} action={{ label: 'Test API', onClick: () => onAction(async () => { const result = await window.desktopApi.testDescript(); if (!result.ok) throw new Error(result.message) }) }}/><Connection icon={<FolderOpen size={19}/>} title="Recording folder" value={data.settings.recordingsDirectory ? 'Ready' : 'Not detected'} detail={data.settings.recordingsDirectory ?? 'Connect to OBS'} state={data.settings.recordingsDirectory ? 'connected' : 'disconnected'}/><Connection icon={<Link2 size={19}/>} title="Destination" value={data.settings.descriptDestinationRoot || 'Drive root'} detail={destination} state="connected"/></section>
  <section className="stat-grid">{[['Waiting', counts.waiting ?? 0, 'amber'], ['Uploading', counts.uploading ?? 0, 'blue'], ['Processing', counts.processing ?? 0, 'violet'], ['Complete', counts.completed ?? 0, 'green'], ['Failed', counts.failed ?? 0, 'red']].map(([label, count, tone]) => <div className="stat-card" key={String(label)}><span className={`stat-mark ${tone}`}/><strong>{count}</strong><span>{label} today</span></div>)}</section>
  <div className="dashboard-grid"><section className="panel queue-panel"><div className="panel-heading"><div><h2>Queue</h2></div><span className="count-chip">{data.recordings.length} total</span></div><div className="recordings">{data.recordings.length ? data.recordings.slice(0, 8).map((recording) => <RecordingRow key={recording.id} recording={recording} onRetry={() => onAction(() => window.desktopApi.retryRecording(recording.id))}/>) : <div className="empty-state"><Video size={26}/><strong>No recordings</strong></div>}</div></section>
  <section className="panel activity-panel"><div className="panel-heading"><div><h2>Activity</h2></div></div><div className="activity-list">{data.activity.length ? data.activity.map((item) => <div className="activity-item" key={item.id}><span className={`activity-icon ${item.kind}`}>{item.kind === 'success' ? <CheckCircle2 size={14}/> : item.kind === 'error' ? <TriangleAlert size={14}/> : <Activity size={14}/>}</span><div><p>{item.message}</p><span>{new Date(item.createdAt).toLocaleString()}</span></div></div>) : <div className="empty-state compact"><Activity size={24}/><span>No activity</span></div>}</div></section></div></>
}

function Connection({ icon, title, value, detail, state, action }: { icon: React.ReactNode; title: string; value: string; detail: string; state: string; action?: { label: string; onClick: () => void } }) { return <div className="connection-card"><div className="connection-top"><span className="connection-icon">{icon}</span><span className={`pill ${state}`}>{state === 'connected' ? 'Ready' : state === 'saved' ? 'Saved' : state === 'rejected' ? 'Rejected' : state === 'connecting' ? 'Connecting' : 'Needs setup'}</span></div><p>{title}</p><strong>{value}</strong><span className="truncate">{detail}</span>{action && <button className="chip-action" disabled={state === 'connecting'} onClick={action.onClick}>{action.label}</button>}</div> }
function RecordingRow({ recording, onRetry }: { recording: Recording; onRetry: () => void }) { return <div className="recording-row"><div className="file-icon"><Video size={17}/></div><div className="recording-name"><strong>{recording.originalFilename}</strong><span>{new Date(recording.recordedAt).toLocaleString()} · {(recording.fileSize / 1_048_576).toFixed(1)} MB</span></div><div className="recording-destination"><span>Descript destination</span><strong>{recording.descriptFolderPath}</strong></div><div className="recording-status"><span className={`status-badge ${recording.status}`}>{recording.status}</span>{recording.status === 'failed' && <button className="text-button" onClick={onRetry}>Retry</button>}</div></div> }

function Settings({ data, busy, onSave, onCancel, onTest, onObs }: { data: AppSnapshot; busy: boolean; onSave: (input: SettingsInput) => Promise<void>; onCancel: () => void; onTest: (token?: string) => Promise<void>; onObs: (input: { host: string; port: number; password?: string }) => Promise<void> }) {
  const [form, setForm] = useState<SettingsInput>({ ...data.settings, descriptToken: '', obsPassword: '' })
  const [warning, setWarning] = useState<string | null>(null)
  const update = <K extends keyof SettingsInput>(key: K, value: SettingsInput[K]) => setForm((previous) => ({ ...previous, [key]: value }))
  const normal = form.descriptDestinationRoot.trim().replace(/[\\/]+/g, '/').replace(/^\/+|\/+$/g, '')
  const preview = [normal, today(form)].filter(Boolean).join('/')
  return <><header className="settings-header"><div><p className="eyebrow">CONFIGURATION</p><h1>Configuration</h1></div></header>
  <div className="settings-layout"><section className="settings-stack"><SettingCard title="Recordings" description="OBS output folder."><label>Recording folder</label><div className="preview-box"><FolderOpen size={16}/>{data.settings.recordingsDirectory ?? 'Connect to OBS to detect'}</div><p className="field-help">Updated when OBS connects. Upload begins after OBS reports that recording has stopped.</p></SettingCard>
  <SettingCard title="Reconciliation" description="Optional historical recording folder."><label>Folder</label><div className="folder-field"><input value={form.reconciliationDirectory ?? data.settings.recordingsDirectory ?? ''} readOnly placeholder="OBS recording folder"/><button className="button secondary" onClick={async () => { const path = await window.desktopApi.chooseReconciliationDirectory(); if (path) update('reconciliationDirectory', path) }}><FolderOpen size={16}/>Browse</button></div><p className="field-help">Scanned only when Reconcile is run. Defaults to the OBS recording folder.</p></SettingCard>
  <SettingCard title="Descript destination" description="Date-based project folders."><label>Root folder (optional)</label><input value={form.descriptDestinationRoot} onChange={(event) => { update('descriptDestinationRoot', event.target.value); setWarning(null) }} placeholder="Drive root"/><p className="field-help">Leave blank to create date folders at the Drive root. Example: Studio Uploads or Client Work/Acme</p>{normal.split('/').filter(Boolean).length > 4 && <p className="inline-warning">Deep path</p>}<label>Date folder format</label><select value={form.recordingDateFormat} onChange={(event) => update('recordingDateFormat', event.target.value as RecordingDateFormat)}><option value="yyyy-MM-dd">YYYY-MM-DD (2026-07-13)</option><option value="M.d.yyyy">M.D.YYYY (7.13.2026)</option><option value="MM.dd.yyyy">MM.DD.YYYY (07.13.2026)</option></select><label>Folder preview</label><div className="preview-box"><FolderOpen size={16}/>{preview}</div><label>Timezone</label><input value={form.recordingTimezone} onChange={(event) => update('recordingTimezone', event.target.value)} placeholder="America/Los_Angeles"/><p className="field-help">Date-folder timezone.</p></SettingCard>
  <SettingCard title="Descript API" description="OS credential store."><label>API token</label>{data.hasDescriptToken && <p className="field-help token-saved">{data.connections.descript === 'rejected' ? 'The stored token was rejected. Enter a replacement below.' : 'A token is stored securely in Keychain. Enter a value only to replace it.'}</p>}<input type="password" value={form.descriptToken} onChange={(event) => update('descriptToken', event.target.value)} placeholder={data.hasDescriptToken ? 'Replace stored token' : 'Paste API token'}/><p className="field-help">Descript → Settings → API tokens</p><button className="button secondary" disabled={busy} onClick={() => onTest(form.descriptToken)}><Cloud size={16}/>{form.descriptToken?.trim() ? 'Test & save token' : data.hasDescriptToken ? 'Test saved token' : 'Test token'}</button></SettingCard>
  <SettingCard title="OBS WebSocket" description="OBS Studio 28+."><div className="split-fields"><div><label>Host</label><input value={form.obsHost} onChange={(event) => update('obsHost', event.target.value)}/></div><div><label>Port</label><input type="number" value={form.obsPort} onChange={(event) => update('obsPort', Number(event.target.value))}/></div></div><label>Password</label><input type="password" value={form.obsPassword} onChange={(event) => update('obsPassword', event.target.value)} placeholder="Replace stored password"/><button className="button secondary" disabled={busy} onClick={() => onObs({ host: form.obsHost, port: form.obsPort, password: form.obsPassword })}><MonitorUp size={16}/>Connect & detect folder</button></SettingCard></section>
  <aside className="settings-aside"><div className="help-card"><div className="help-icon"><Cloud size={19}/></div><h2>Requirements</h2><ol><li>OBS: Tools → WebSocket Server Settings</li><li>Descript API token scoped to the target Drive</li><li>Available Descript media minutes</li></ol><p>Destination changes apply to newly discovered recordings.</p></div></aside></div>
  <footer className="settings-footer">{warning && <span className="inline-warning">{warning}</span>}<div><button className="button ghost" onClick={onCancel}>Back to top</button><button className="button primary" disabled={busy} onClick={() => { if (/[\x00-\x1F\x7F]/.test(normal)) { setWarning('The destination root contains a control character.'); return } void onSave({ ...form, descriptDestinationRoot: normal }) }}>{busy ? <Loader2 size={16} className="spin"/> : null}Save settings</button></div></footer></>
}
function SettingCard({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section className="setting-card"><div className="setting-card-header"><h2>{title}</h2><p>{description}</p></div><div className="form-fields">{children}</div></section> }
